### ISSUE TITLE
Vagrant up with manifest worked a few weeks ago, same one now doesn't, what would be the reason?

### ISSUE THREAD

**Issue by therobyouknow** [puphpet/puppet-puphpet#30]
I downloaded a Vagrant manifest end of October and was able to get it to work.

Today, I delete the VM (for specific reasons) to start again but use the exact same manifest.

However, on doing a vagrant up, I get a sea of red text but find that changing the version of mysql I had from 5.6 to 5.5 in the config.yaml, makes the vagrant up work.

But why did 5.6 work a few weeks ago and not now.

One guess is that vagrant up pulls down external online dependencies (apart from the box, which I already have) and those dependencies had been adjusted. But why not keep those dependencies the same? Sure, if those dependencies are improved upon I would accept that, but why not offer the user the option to use those or stick with what they used a few weeks ago?

**Comment by jtreminio** [comment]
Please see https://github.com/puphpet/puphpet/issues/1962
