### ISSUE TITLE
Php:Devel dependency in pecl not found

### ISSUE THREAD

**Issue by mkdeddens** [puphpet/puppet-puphpet#36]
Refer [this ](https://github.com/puphpet/puphpet/issues/2142#issuecomment-178479889) and [this ](https://github.com/puphpet/puphpet/issues/2142#issuecomment-178503633) comment on [this puphpet issue](https://github.com/puphpet/puphpet/issues/2142).

Seems php5 packages are requiring php:devel to be in place, which is not found by [line 35 in pecl.pp.](https://github.com/puphpet/puppet-puphpet/blob/master/manifests/php/pecl.pp#L139).

**Comment by mkdeddens** [comment]
Refer [my comment](https://github.com/puphpet/puphpet/issues/2142#issuecomment-178570115) in the mentioned puphpet issue thread.
Seems changing puppet-puphpet/manifests/php/pecl.pp:139 to what's below does the trick:

require => Package[$puphpet::php::settings::package_devel]

**Comment by jtreminio** [comment]
Thanks. I had this locally but never pushed! Sorry!
